In [2]:
import numpy as np

1 Dimensional Array (1D)

In [4]:
NP1 = np.array([1,2,3,4,5,6])
print(type(NP1))

<class 'numpy.ndarray'>


2 Dimensional Array (2D)

Shape means (rows,columns) - 2 rows , 3 columns

In [6]:
NP2 = np.array([[1,2,3],[4,5,6]])
NP2
print(NP2.shape)

(2, 3)


In [7]:
print(NP2.size)

6


Shows the Dimension of the array -  2 means 2D , 1 means 1D

In [9]:
print(NP2.ndim)
print(NP1.ndim)

2
1


Accessing items in an 1D array

In [13]:
print(NP1[0])
print(NP1[2])

1
3


In [16]:
print(NP1[3:5])

[4 5]


Accessing items in a 2D array

In [17]:
NP2

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
print(NP2[0]) # prints row 1
print(NP2[1]) # prints row 2

[1 2 3]
[4 5 6]


In [22]:
NP2[0,2] # first row , third element

3

Returns the first digit of all the coloumns

In [25]:
NP2[:,0] # colon  ":"  means  "all"

array([1, 4])

In [28]:
NP2[0,:] # similar to NP2[0]

array([1, 2, 3])

In [30]:
NP2[1,1] # second row , second column

5

NP2[row,column]

In [31]:
NP2[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
NP2[0:2,1:3] # both rows , skip first column

array([[2, 3],
       [5, 6]])

In [38]:
NP3 = np.array([[1,2],[3,4]])
NP4 = np.array([[5,6],[7,8]])
print(NP3)
print() # spacing
print(NP4)

[[1 2]
 [3 4]]

[[5 6]
 [7 8]]


In [39]:
NP3+NP4 # add up each elements in coresponding positions

array([[ 6,  8],
       [10, 12]])

In [40]:
NP3-NP4 # substracts each elements in corresponding positions

array([[-4, -4],
       [-4, -4]])

In [41]:
NP3/NP4 # divides each elements in corresponding positions

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [42]:
NP3*NP4 # multiplies each elements in corresponding positions

array([[ 5, 12],
       [21, 32]])

If you want to do matrix multiplication

In [43]:
NP3@NP4

array([[19, 22],
       [43, 50]])